app = "rally-point-ord"
primary_region = "ord"
processes = []

[env]
  IS_FLY = true
  RP_HOST = "fly-global-services"

[[services]]
  internal_port = 14098
  processes = ["app"]
  protocol = "udp"

  [[services.ports]]
    port = 14098
